package com.kkulddip.common.exception;

import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

public enum ErrorCode {
    
    // 공통 도메인 에러
    COMMON_INVALID_INPUT(BAD_REQUEST, "COMMON_INVALID_INPUT", "잘못된 입력값입니다."),
    COMMON_INVALID_TYPE(BAD_REQUEST, "COMMON_INVALID_TYPE", "잘못된 타입입니다."),
    COMMON_NOT_FOUND(NOT_FOUND, "COMMON_NOT_FOUND", "요청한 리소스를 찾을 수 없습니다."),
    COMMON_METHOD_NOT_ALLOWED(METHOD_NOT_ALLOWED, "COMMON_METHOD_NOT_ALLOWED", "허용되지 않는 메서드입니다."),
    COMMON_INTERNAL_SERVER_ERROR(INTERNAL_SERVER_ERROR, "COMMON_INTERNAL_SERVER_ERROR", "내부 서버 오류입니다."),
    
    // 사용자 도메인 에러
    USER_REGISTER_TYPE_ERROR(BAD_REQUEST, "USER_REGISTER_TYPE_ERROR", "사용자 등록 타입 오류입니다."),
    USER_NOT_FOUND(NOT_FOUND, "USER_NOT_FOUND", "사용자를 찾을 수 없습니다."),
    USER_DUPLICATE_EMAIL(CONFLICT, "USER_DUPLICATE_EMAIL", "이미 존재하는 이메일입니다."),
    USER_INVALID_PASSWORD(BAD_REQUEST, "USER_INVALID_PASSWORD", "비밀번호가 올바르지 않습니다."),
    DUPLICATE_PHONE_NUMBER(CONFLICT, "DUPLICATE_PHONE_NUMBER", "이미 존재하는 전화번호입니다."),
    
    // 인증 도메인 에러
    AUTH_UNAUTHORIZED(UNAUTHORIZED, "AUTH_UNAUTHORIZED", "인증이 필요합니다."),
    AUTH_INVALID_TOKEN(UNAUTHORIZED, "AUTH_INVALID_TOKEN", "유효하지 않은 토큰입니다."),
    AUTH_EXPIRED_TOKEN(UNAUTHORIZED, "AUTH_EXPIRED_TOKEN", "만료된 토큰입니다."),
    AUTH_ACCESS_DENIED(FORBIDDEN, "AUTH_ACCESS_DENIED", "접근이 거부되었습니다."),
    AUTH_UNAUTHENTICATED_USER(UNAUTHORIZED, "AUTH_UNAUTHENTICATED_USER", "인증되지 않은 사용자입니다."),
    AUTH_INVALID_USER_ROLE(BAD_REQUEST, "AUTH_INVALID_USER_ROLE", "유효하지 않은 사용자 역할입니다."),
    AUTH_INSUFFICIENT_PERMISSION(FORBIDDEN, "AUTH_INSUFFICIENT_PERMISSION", "권한이 부족합니다."),
    AUTH_TOKEN_MISSING(UNAUTHORIZED, "AUTH_TOKEN_MISSING", "인증 토큰이 필요합니다."),
    AUTH_INVALID_HEADER_FORMAT(UNAUTHORIZED, "AUTH_INVALID_HEADER_FORMAT", "Authorization 헤더 형식이 올바르지 않습니다."),
    AUTH_INVALID_SIGNATURE(UNAUTHORIZED, "AUTH_INVALID_SIGNATURE", "토큰 서명이 유효하지 않습니다."),
    AUTH_MALFORMED_TOKEN(UNAUTHORIZED, "AUTH_MALFORMED_TOKEN", "토큰 형식이 올바르지 않습니다."),
    AUTH_MISSING_REQUIRED_CLAIM(UNAUTHORIZED, "AUTH_MISSING_REQUIRED_CLAIM", "필수 토큰 정보가 누락되었습니다."),

    // OAuth2 도메인 에러
    AUTH_OAUTH2_AUTHENTICATION_FAILED(UNAUTHORIZED, "AUTH_OAUTH2_AUTHENTICATION_FAILED", "OAuth2 인증에 실패했습니다."),
    AUTH_OAUTH2_USER_INFO_FAILED(BAD_REQUEST, "AUTH_OAUTH2_USER_INFO_FAILED", "OAuth2 사용자 정보 처리에 실패했습니다."),
    AUTH_OAUTH2_UNSUPPORTED_PROVIDER(BAD_REQUEST, "AUTH_OAUTH2_UNSUPPORTED_PROVIDER", "지원하지 않는 OAuth2 제공자입니다."),
    AUTH_OAUTH2_USER_CREATION_FAILED(INTERNAL_SERVER_ERROR, "AUTH_OAUTH2_USER_CREATION_FAILED", "OAuth2 사용자 생성에 실패했습니다."),
    AUTH_OAUTH2_USER_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "AUTH_OAUTH2_USER_UPDATE_FAILED", "OAuth2 사용자 정보 업데이트에 실패했습니다."),
    
    // 주문 도메인 에러 - 기본
    ORDER_NOT_FOUND(NOT_FOUND, "ORDER_NOT_FOUND", "주문을 찾을 수 없습니다."),
    ORDER_ALREADY_EXISTS(CONFLICT, "ORDER_ALREADY_EXISTS", "이미 존재하는 주문입니다."),
    
    // 주문 도메인 에러 - 상태 관련
    ORDER_INVALID_STATUS(BAD_REQUEST, "ORDER_INVALID_STATUS", "잘못된 주문 상태입니다."),
    ORDER_CANNOT_BE_MODIFIED(BAD_REQUEST, "ORDER_CANNOT_BE_MODIFIED", "주문을 수정할 수 없습니다."),
    ORDER_CANNOT_BE_CANCELLED(BAD_REQUEST, "ORDER_CANNOT_BE_CANCELLED", "주문을 취소할 수 없습니다."),
    ORDER_CANNOT_BE_CONFIRMED(BAD_REQUEST, "ORDER_CANNOT_BE_CONFIRMED", "주문을 확인할 수 없습니다."),
    ORDER_CANNOT_BE_DELIVERED(BAD_REQUEST, "ORDER_CANNOT_BE_DELIVERED", "주문을 배송 완료 처리할 수 없습니다."),
    ORDER_STATUS_TRANSITION_INVALID(BAD_REQUEST, "ORDER_STATUS_TRANSITION_INVALID", "잘못된 주문 상태 전환입니다."),
    
    // 주문 도메인 에러 - 주문 항목 관련
    ORDER_EMPTY_ITEMS(BAD_REQUEST, "ORDER_EMPTY_ITEMS", "주문 항목이 비어있습니다."),
    ORDER_ITEM_NOT_FOUND(NOT_FOUND, "ORDER_ITEM_NOT_FOUND", "주문 항목을 찾을 수 없습니다."),
    ORDER_INVALID_QUANTITY(BAD_REQUEST, "ORDER_INVALID_QUANTITY", "잘못된 주문 수량입니다."),
    ORDER_INVALID_UNIT_PRICE(BAD_REQUEST, "ORDER_INVALID_UNIT_PRICE", "잘못된 단가입니다."),
    ORDER_ITEM_QUANTITY_EXCEEDED(BAD_REQUEST, "ORDER_ITEM_QUANTITY_EXCEEDED", "주문 수량이 초과되었습니다."),
    
    // 주문 도메인 에러 - 금액 관련
    ORDER_PRICE_VALIDATION_FAILED(BAD_REQUEST, "ORDER_PRICE_VALIDATION_FAILED", "상품 가격 검증에 실패했습니다."),
    ORDER_PRICE_MISMATCH(BAD_REQUEST, "ORDER_PRICE_MISMATCH", "요청한 가격이 실제 상품 가격과 일치하지 않습니다."),
    ORDER_TOTAL_AMOUNT_INVALID(BAD_REQUEST, "ORDER_TOTAL_AMOUNT_INVALID", "주문 총액이 유효하지 않습니다."),
    ORDER_AMOUNT_CALCULATION_ERROR(INTERNAL_SERVER_ERROR, "ORDER_AMOUNT_CALCULATION_ERROR", "주문 금액 계산 중 오류가 발생했습니다."),
    
    // 주문 도메인 에러 - 권한 관련
    ORDER_ACCESS_DENIED(FORBIDDEN, "ORDER_ACCESS_DENIED", "주문에 대한 접근 권한이 없습니다."),
    ORDER_CUSTOMER_MISMATCH(FORBIDDEN, "ORDER_CUSTOMER_MISMATCH", "주문 고객 정보가 일치하지 않습니다."),
    
    // 주문 도메인 에러 - 비즈니스 규칙
    ORDER_CREATION_FAILED(INTERNAL_SERVER_ERROR, "ORDER_CREATION_FAILED", "주문 생성에 실패했습니다."),
    ORDER_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "ORDER_UPDATE_FAILED", "주문 업데이트에 실패했습니다."),
    ORDER_DELETION_FAILED(INTERNAL_SERVER_ERROR, "ORDER_DELETION_FAILED", "주문 삭제에 실패했습니다."),
    ORDER_PERSISTENCE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_PERSISTENCE_ERROR", "주문 저장 중 오류가 발생했습니다."),
    
    // 주문 도메인 에러 - Infrastructure 계층
    ORDER_CACHE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_CACHE_ERROR", "주문 캐시 처리 중 오류가 발생했습니다."),
    ORDER_DATABASE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_DATABASE_ERROR", "주문 데이터베이스 처리 중 오류가 발생했습니다."),
    ORDER_EXTERNAL_API_ERROR(BAD_GATEWAY, "ORDER_EXTERNAL_API_ERROR", "외부 API 호출 중 오류가 발생했습니다."),
    ORDER_EVENT_PUBLISH_FAILED(INTERNAL_SERVER_ERROR, "ORDER_EVENT_PUBLISH_FAILED", "주문 이벤트 발행에 실패했습니다."),
    
    // 결제 도메인 에러
    PAYMENT_NOT_FOUND(NOT_FOUND, "PAYMENT_NOT_FOUND", "결제 정보를 찾을 수 없습니다."),
    PAYMENT_ALREADY_CONFIRMED(BAD_REQUEST, "PAYMENT_ALREADY_CONFIRMED", "이미 확정된 결제입니다."),
    PAYMENT_ALREADY_CANCELLED(BAD_REQUEST, "PAYMENT_ALREADY_CANCELLED", "이미 취소된 결제입니다."),
    PAYMENT_INVALID_STATUS(BAD_REQUEST, "PAYMENT_INVALID_STATUS", "잘못된 결제 상태입니다."),
    PAYMENT_AMOUNT_MISMATCH(BAD_REQUEST, "PAYMENT_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
    PAYMENT_ORDER_ID_INVALID(BAD_REQUEST, "PAYMENT_ORDER_ID_INVALID", "잘못된 주문 ID입니다."),
    PAYMENT_API_ERROR(BAD_GATEWAY, "PAYMENT_API_ERROR", "결제 API 호출 중 오류가 발생했습니다."),
    PAYMENT_API_TIMEOUT(GATEWAY_TIMEOUT, "PAYMENT_API_TIMEOUT", "결제 API 호출 시간이 초과되었습니다."),
    PAYMENT_API_UNAUTHORIZED(UNAUTHORIZED, "PAYMENT_API_UNAUTHORIZED", "결제 API 인증에 실패했습니다."),
    PAYMENT_CONFIRM_FAILED(BAD_REQUEST, "PAYMENT_CONFIRM_FAILED", "결제 승인에 실패했습니다."),
    PAYMENT_CANCEL_FAILED(BAD_REQUEST, "PAYMENT_CANCEL_FAILED", "결제 취소에 실패했습니다."),
    PAYMENT_INVALID_KEY(BAD_REQUEST, "PAYMENT_INVALID_KEY", "유효하지 않은 결제 키입니다."),
    
    // 가게 도메인 에러
    STORE_NOT_FOUND(NOT_FOUND, "STORE_NOT_FOUND", "가게를 찾을 수 없습니다."),
    STORE_NOT_ACTIVE(BAD_REQUEST, "STORE_NOT_ACTIVE", "비활성화된 가게입니다."),
    STORE_INVALID_ID(BAD_REQUEST, "STORE_INVALID_ID", "유효하지 않은 가게 ID입니다."),
    STORE_INVALID_SORT_TYPE(BAD_REQUEST, "STORE_INVALID_SORT_TYPE", "지원하지 않는 정렬 타입입니다."),
    STORE_INVALID_PAGE_SIZE(BAD_REQUEST, "STORE_INVALID_PAGE_SIZE", "페이지 크기는 1 이상 50 이하여야 합니다."),
    STORE_SEARCH_KEYWORD_EMPTY(BAD_REQUEST, "STORE_SEARCH_KEYWORD_EMPTY", "검색 키워드는 필수입니다."),
    STORE_CATEGORY_EMPTY(BAD_REQUEST, "STORE_CATEGORY_EMPTY", "카테고리는 필수입니다."),
    STORE_CURSOR_DECODE_FAILED(BAD_REQUEST, "STORE_CURSOR_DECODE_FAILED", "커서 디코딩에 실패했습니다."),
    STORE_DISTANCE_CALCULATION_FAILED(INTERNAL_SERVER_ERROR, "STORE_DISTANCE_CALCULATION_FAILED", "거리 계산에 실패했습니다."),
    
    // 띱박스 도메인 에러
    DDIPBOX_NOT_FOUND(NOT_FOUND, "DDIPBOX_NOT_FOUND", "띱박스를 찾을 수 없습니다."),
    DDIPBOX_NOT_ACTIVE(BAD_REQUEST, "DDIPBOX_NOT_ACTIVE", "비활성화된 띱박스입니다."),
    DDIPBOX_SOLD_OUT(BAD_REQUEST, "DDIPBOX_SOLD_OUT", "품절된 띱박스입니다."),
    DDIPBOX_INVALID_QUANTITY(BAD_REQUEST, "DDIPBOX_INVALID_QUANTITY", "유효하지 않은 수량입니다."),
    
    // 즐겨찾기 도메인 에러
    FAVORITE_NOT_FOUND(NOT_FOUND, "FAVORITE_NOT_FOUND", "즐겨찾기를 찾을 수 없습니다."),
    FAVORITE_ALREADY_EXISTS(CONFLICT, "FAVORITE_ALREADY_EXISTS", "이미 즐겨찾기에 추가된 가게입니다."),
    FAVORITE_INVALID_CUSTOMER_ID(BAD_REQUEST, "FAVORITE_INVALID_CUSTOMER_ID", "유효하지 않은 고객 ID입니다."),
    FAVORITE_INVALID_STORE_ID(BAD_REQUEST, "FAVORITE_INVALID_STORE_ID", "유효하지 않은 가게 ID입니다."),
    FAVORITE_INVALID_SORT_TYPE(BAD_REQUEST, "FAVORITE_INVALID_SORT_TYPE", "지원하지 않는 정렬 타입입니다."),
    FAVORITE_INVALID_PAGE_SIZE(BAD_REQUEST, "FAVORITE_INVALID_PAGE_SIZE", "페이지 크기는 1 이상 100 이하여야 합니다."),
    FAVORITE_CURSOR_DECODE_FAILED(BAD_REQUEST, "FAVORITE_CURSOR_DECODE_FAILED", "커서 디코딩에 실패했습니다.");
    
    private final HttpStatus status;
    private final String code;
    private final String message;
    
    ErrorCode(HttpStatus status, String code, String message) {
        this.status = status;
        this.code = code;
        this.message = message;
    }
    
    public HttpStatus getStatus() {
        return status;
    }
    
    public String getCode() {
        return code;
    }
    
    public String getMessage() {
        return message;
    }
} 