package com.kkulddip.common.exception;

import org.springframework.http.HttpStatus;
import static org.springframework.http.HttpStatus.*;

public enum ErrorCode {
    
    // 공통 도메인 에러
    COMMON_INVALID_INPUT(BAD_REQUEST, "COMMON_INVALID_INPUT", "잘못된 입력값입니다."),
    COMMON_INVALID_TYPE(BAD_REQUEST, "COMMON_INVALID_TYPE", "잘못된 타입입니다."),
    COMMON_NOT_FOUND(NOT_FOUND, "COMMON_NOT_FOUND", "요청한 리소스를 찾을 수 없습니다."),
    COMMON_METHOD_NOT_ALLOWED(METHOD_NOT_ALLOWED, "COMMON_METHOD_NOT_ALLOWED", "허용되지 않는 메서드입니다."),
    COMMON_INTERNAL_SERVER_ERROR(INTERNAL_SERVER_ERROR, "COMMON_INTERNAL_SERVER_ERROR", "내부 서버 오류입니다."),
    COMMON_INVALID_REQUEST(BAD_REQUEST, "COMMON_INVALID_REQUEST", "잘못된 요청입니다."),
    COMMON_ENTITY_NOT_FOUND(NOT_FOUND, "COMMON_ENTITY_NOT_FOUND", "요청한 엔티티를 찾을 수 없습니다."),
    
    // 사용자 도메인 에러
    USER_REGISTER_TYPE_ERROR(BAD_REQUEST, "USER_REGISTER_TYPE_ERROR", "사용자 등록 타입 오류입니다."),
    USER_NOT_FOUND(NOT_FOUND, "USER_NOT_FOUND", "사용자를 찾을 수 없습니다."),
    USER_DUPLICATE_EMAIL(CONFLICT, "USER_DUPLICATE_EMAIL", "이미 존재하는 이메일입니다."),
    USER_INVALID_PASSWORD(BAD_REQUEST, "USER_INVALID_PASSWORD", "비밀번호가 올바르지 않습니다."),
    DUPLICATE_PHONE_NUMBER(CONFLICT, "DUPLICATE_PHONE_NUMBER", "이미 존재하는 전화번호입니다."),
    
    // 인증 도메인 에러
    AUTH_UNAUTHORIZED(UNAUTHORIZED, "AUTH_UNAUTHORIZED", "인증이 필요합니다."),
    AUTH_INVALID_TOKEN(UNAUTHORIZED, "AUTH_INVALID_TOKEN", "유효하지 않은 토큰입니다."),
    AUTH_EXPIRED_TOKEN(UNAUTHORIZED, "AUTH_EXPIRED_TOKEN", "만료된 토큰입니다."),
    AUTH_ACCESS_DENIED(FORBIDDEN, "AUTH_ACCESS_DENIED", "접근이 거부되었습니다."),
    AUTH_UNAUTHENTICATED_USER(UNAUTHORIZED, "AUTH_UNAUTHENTICATED_USER", "인증되지 않은 사용자입니다."),
    AUTH_INVALID_USER_ROLE(BAD_REQUEST, "AUTH_INVALID_USER_ROLE", "유효하지 않은 사용자 역할입니다."),
    AUTH_INSUFFICIENT_PERMISSION(FORBIDDEN, "AUTH_INSUFFICIENT_PERMISSION", "권한이 부족합니다."),
    AUTH_TOKEN_MISSING(UNAUTHORIZED, "AUTH_TOKEN_MISSING", "인증 토큰이 필요합니다."),
    AUTH_INVALID_HEADER_FORMAT(UNAUTHORIZED, "AUTH_INVALID_HEADER_FORMAT", "Authorization 헤더 형식이 올바르지 않습니다."),
    AUTH_INVALID_SIGNATURE(UNAUTHORIZED, "AUTH_INVALID_SIGNATURE", "토큰 서명이 유효하지 않습니다."),
    AUTH_MALFORMED_TOKEN(UNAUTHORIZED, "AUTH_MALFORMED_TOKEN", "토큰 형식이 올바르지 않습니다."),
    AUTH_MISSING_REQUIRED_CLAIM(UNAUTHORIZED, "AUTH_MISSING_REQUIRED_CLAIM", "필수 토큰 정보가 누락되었습니다."),

    // OAuth2 도메인 에러
    AUTH_OAUTH2_AUTHENTICATION_FAILED(UNAUTHORIZED, "AUTH_OAUTH2_AUTHENTICATION_FAILED", "OAuth2 인증에 실패했습니다."),
    AUTH_OAUTH2_USER_INFO_FAILED(BAD_REQUEST, "AUTH_OAUTH2_USER_INFO_FAILED", "OAuth2 사용자 정보 처리에 실패했습니다."),
    AUTH_OAUTH2_UNSUPPORTED_PROVIDER(BAD_REQUEST, "AUTH_OAUTH2_UNSUPPORTED_PROVIDER", "지원하지 않는 OAuth2 제공자입니다."),
    AUTH_OAUTH2_USER_CREATION_FAILED(INTERNAL_SERVER_ERROR, "AUTH_OAUTH2_USER_CREATION_FAILED", "OAuth2 사용자 생성에 실패했습니다."),
    AUTH_OAUTH2_USER_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "AUTH_OAUTH2_USER_UPDATE_FAILED", "OAuth2 사용자 정보 업데이트에 실패했습니다."),
    
    // 주문 도메인 에러 - 기본
    ORDER_NOT_FOUND(NOT_FOUND, "ORDER_NOT_FOUND", "주문을 찾을 수 없습니다."),
    ORDER_ALREADY_EXISTS(CONFLICT, "ORDER_ALREADY_EXISTS", "이미 존재하는 주문입니다."),
    
    // 주문 도메인 에러 - 상태 관련
    ORDER_INVALID_STATUS(BAD_REQUEST, "ORDER_INVALID_STATUS", "잘못된 주문 상태입니다."),
    ORDER_CANNOT_BE_MODIFIED(BAD_REQUEST, "ORDER_CANNOT_BE_MODIFIED", "주문을 수정할 수 없습니다."),
    ORDER_CANNOT_BE_CANCELLED(BAD_REQUEST, "ORDER_CANNOT_BE_CANCELLED", "주문을 취소할 수 없습니다."),
    ORDER_CANNOT_BE_CONFIRMED(BAD_REQUEST, "ORDER_CANNOT_BE_CONFIRMED", "주문을 확인할 수 없습니다."),
    ORDER_CANNOT_BE_DELIVERED(BAD_REQUEST, "ORDER_CANNOT_BE_DELIVERED", "주문을 배송 완료 처리할 수 없습니다."),
    ORDER_STATUS_TRANSITION_INVALID(BAD_REQUEST, "ORDER_STATUS_TRANSITION_INVALID", "잘못된 주문 상태 전환입니다."),
    
    // 주문 도메인 에러 - 주문 항목 관련
    ORDER_EMPTY_ITEMS(BAD_REQUEST, "ORDER_EMPTY_ITEMS", "주문 항목이 비어있습니다."),
    ORDER_ITEM_NOT_FOUND(NOT_FOUND, "ORDER_ITEM_NOT_FOUND", "주문 항목을 찾을 수 없습니다."),
    ORDER_INVALID_QUANTITY(BAD_REQUEST, "ORDER_INVALID_QUANTITY", "잘못된 주문 수량입니다."),
    ORDER_INVALID_UNIT_PRICE(BAD_REQUEST, "ORDER_INVALID_UNIT_PRICE", "잘못된 단가입니다."),
    ORDER_ITEM_QUANTITY_EXCEEDED(BAD_REQUEST, "ORDER_ITEM_QUANTITY_EXCEEDED", "주문 수량이 초과되었습니다."),
    
    // 주문 도메인 에러 - 금액 관련
    ORDER_PRICE_VALIDATION_FAILED(BAD_REQUEST, "ORDER_PRICE_VALIDATION_FAILED", "상품 가격 검증에 실패했습니다."),
    ORDER_PRICE_MISMATCH(BAD_REQUEST, "ORDER_PRICE_MISMATCH", "요청한 가격이 실제 상품 가격과 일치하지 않습니다."),
    ORDER_TOTAL_AMOUNT_INVALID(BAD_REQUEST, "ORDER_TOTAL_AMOUNT_INVALID", "주문 총액이 유효하지 않습니다."),
    ORDER_AMOUNT_CALCULATION_ERROR(INTERNAL_SERVER_ERROR, "ORDER_AMOUNT_CALCULATION_ERROR", "주문 금액 계산 중 오류가 발생했습니다."),
    
    // 주문 도메인 에러 - 권한 관련
    ORDER_ACCESS_DENIED(FORBIDDEN, "ORDER_ACCESS_DENIED", "주문에 대한 접근 권한이 없습니다."),
    ORDER_CUSTOMER_MISMATCH(FORBIDDEN, "ORDER_CUSTOMER_MISMATCH", "주문 고객 정보가 일치하지 않습니다."),
    
    // 주문 도메인 에러 - 비즈니스 규칙
    ORDER_CREATION_FAILED(INTERNAL_SERVER_ERROR, "ORDER_CREATION_FAILED", "주문 생성에 실패했습니다."),
    ORDER_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "ORDER_UPDATE_FAILED", "주문 업데이트에 실패했습니다."),
    ORDER_DELETION_FAILED(INTERNAL_SERVER_ERROR, "ORDER_DELETION_FAILED", "주문 삭제에 실패했습니다."),
    ORDER_PERSISTENCE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_PERSISTENCE_ERROR", "주문 저장 중 오류가 발생했습니다."),
    
    // 주문 도메인 에러 - Infrastructure 계층
    ORDER_CACHE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_CACHE_ERROR", "주문 캐시 처리 중 오류가 발생했습니다."),
    ORDER_DATABASE_ERROR(INTERNAL_SERVER_ERROR, "ORDER_DATABASE_ERROR", "주문 데이터베이스 처리 중 오류가 발생했습니다."),
    ORDER_EXTERNAL_API_ERROR(BAD_GATEWAY, "ORDER_EXTERNAL_API_ERROR", "외부 API 호출 중 오류가 발생했습니다."),
    ORDER_EVENT_PUBLISH_FAILED(INTERNAL_SERVER_ERROR, "ORDER_EVENT_PUBLISH_FAILED", "주문 이벤트 발행에 실패했습니다."),
    
    // 결제 도메인 에러
    PAYMENT_NOT_FOUND(NOT_FOUND, "PAYMENT_NOT_FOUND", "결제 정보를 찾을 수 없습니다."),
    PAYMENT_ALREADY_CONFIRMED(BAD_REQUEST, "PAYMENT_ALREADY_CONFIRMED", "이미 확정된 결제입니다."),
    PAYMENT_ALREADY_CANCELLED(BAD_REQUEST, "PAYMENT_ALREADY_CANCELLED", "이미 취소된 결제입니다."),
    PAYMENT_INVALID_STATUS(BAD_REQUEST, "PAYMENT_INVALID_STATUS", "잘못된 결제 상태입니다."),
    PAYMENT_AMOUNT_MISMATCH(BAD_REQUEST, "PAYMENT_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
    PAYMENT_ORDER_ID_INVALID(BAD_REQUEST, "PAYMENT_ORDER_ID_INVALID", "잘못된 주문 ID입니다."),
    PAYMENT_API_ERROR(BAD_GATEWAY, "PAYMENT_API_ERROR", "결제 API 호출 중 오류가 발생했습니다."),
    PAYMENT_API_TIMEOUT(GATEWAY_TIMEOUT, "PAYMENT_API_TIMEOUT", "결제 API 호출 시간이 초과되었습니다."),
    PAYMENT_API_UNAUTHORIZED(UNAUTHORIZED, "PAYMENT_API_UNAUTHORIZED", "결제 API 인증에 실패했습니다."),
    PAYMENT_CONFIRM_FAILED(BAD_REQUEST, "PAYMENT_CONFIRM_FAILED", "결제 승인에 실패했습니다."),
    PAYMENT_CANCEL_FAILED(BAD_REQUEST, "PAYMENT_CANCEL_FAILED", "결제 취소에 실패했습니다."),
    PAYMENT_INVALID_KEY(BAD_REQUEST, "PAYMENT_INVALID_KEY", "유효하지 않은 결제 키입니다."),
    PAYMENT_ALREADY_PROCESSING(CONFLICT, "PAYMENT_ALREADY_PROCESSING", "결제가 이미 처리 중입니다."),
    
    // 가게 도메인 에러
    STORE_NOT_FOUND(NOT_FOUND, "STORE_NOT_FOUND", "가게를 찾을 수 없습니다."),
    STORE_NOT_ACTIVE(BAD_REQUEST, "STORE_NOT_ACTIVE", "비활성화된 가게입니다."),
    STORE_INVALID_ID(BAD_REQUEST, "STORE_INVALID_ID", "유효하지 않은 가게 ID입니다."),
    STORE_INVALID_SORT_TYPE(BAD_REQUEST, "STORE_INVALID_SORT_TYPE", "지원하지 않는 정렬 타입입니다."),
    STORE_INVALID_PAGE_SIZE(BAD_REQUEST, "STORE_INVALID_PAGE_SIZE", "페이지 크기는 1 이상 50 이하여야 합니다."),
    STORE_SEARCH_KEYWORD_EMPTY(BAD_REQUEST, "STORE_SEARCH_KEYWORD_EMPTY", "검색 키워드는 필수입니다."),
    STORE_CATEGORY_EMPTY(BAD_REQUEST, "STORE_CATEGORY_EMPTY", "카테고리는 필수입니다."),
    STORE_CURSOR_DECODE_FAILED(BAD_REQUEST, "STORE_CURSOR_DECODE_FAILED", "커서 디코딩에 실패했습니다."),
    STORE_DISTANCE_CALCULATION_FAILED(INTERNAL_SERVER_ERROR, "STORE_DISTANCE_CALCULATION_FAILED", "거리 계산에 실패했습니다."),
    
    // 띱박스 도메인 에러
    DDIPBOX_NOT_FOUND(NOT_FOUND, "DDIPBOX_NOT_FOUND", "띱박스를 찾을 수 없습니다."),
    DDIPBOX_NOT_ACTIVE(BAD_REQUEST, "DDIPBOX_NOT_ACTIVE", "비활성화된 띱박스입니다."),
    DDIPBOX_SOLD_OUT(BAD_REQUEST, "DDIPBOX_SOLD_OUT", "품절된 띱박스입니다."),
    DDIPBOX_INVALID_QUANTITY(BAD_REQUEST, "DDIPBOX_INVALID_QUANTITY", "유효하지 않은 수량입니다."),
    
    // 즐겨찾기 도메인 에러
    FAVORITE_NOT_FOUND(NOT_FOUND, "FAVORITE_NOT_FOUND", "즐겨찾기를 찾을 수 없습니다."),
    FAVORITE_ALREADY_EXISTS(CONFLICT, "FAVORITE_ALREADY_EXISTS", "이미 즐겨찾기에 추가된 가게입니다."),
    FAVORITE_INVALID_CUSTOMER_ID(BAD_REQUEST, "FAVORITE_INVALID_CUSTOMER_ID", "유효하지 않은 고객 ID입니다."),
    FAVORITE_INVALID_STORE_ID(BAD_REQUEST, "FAVORITE_INVALID_STORE_ID", "유효하지 않은 가게 ID입니다."),
    FAVORITE_INVALID_SORT_TYPE(BAD_REQUEST, "FAVORITE_INVALID_SORT_TYPE", "지원하지 않는 정렬 타입입니다."),
    FAVORITE_INVALID_PAGE_SIZE(BAD_REQUEST, "FAVORITE_INVALID_PAGE_SIZE", "페이지 크기는 1 이상 100 이하여야 합니다."),
    FAVORITE_CURSOR_DECODE_FAILED(BAD_REQUEST, "FAVORITE_CURSOR_DECODE_FAILED", "커서 디코딩에 실패했습니다."),

    // FCM 토큰 관련 에러
    FCM_TOKEN_INVALID(BAD_REQUEST, "FCM_TOKEN_INVALID", "유효하지 않은 FCM 토큰입니다."),
    FCM_TOKEN_NOT_FOUND(NOT_FOUND, "FCM_TOKEN_NOT_FOUND", "FCM 토큰을 찾을 수 없습니다."),
    FCM_TOKEN_REGISTRATION_FAILED(INTERNAL_SERVER_ERROR, "FCM_TOKEN_REGISTRATION_FAILED", "FCM 토큰 등록에 실패했습니다."),

    // 리뷰 도메인 에러 - 기본 작업
    REVIEW_NOT_FOUND(NOT_FOUND, "REVIEW_NOT_FOUND", "리뷰를 찾을 수 없습니다."),
    REVIEW_CREATE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_CREATE_FAILED", "리뷰 생성에 실패했습니다."),
    REVIEW_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_UPDATE_FAILED", "리뷰 수정에 실패했습니다."),
    REVIEW_DELETE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_DELETE_FAILED", "리뷰 삭제에 실패했습니다."),
    REVIEW_LIST_FETCH_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_LIST_FETCH_FAILED", "리뷰 목록 조회에 실패했습니다."),

    // 리뷰 도메인 에러 - 입력값 검증
    INVALID_STORE_ID(BAD_REQUEST, "INVALID_STORE_ID", "유효하지 않은 매장 ID입니다."),
    INVALID_REVIEW_ID(BAD_REQUEST, "INVALID_REVIEW_ID", "유효하지 않은 리뷰 ID입니다."),
    INVALID_USER_ID(BAD_REQUEST, "INVALID_USER_ID", "유효하지 않은 사용자 ID입니다."),
    INVALID_REQUEST(BAD_REQUEST, "INVALID_REQUEST", "요청 데이터가 없습니다."),
    INVALID_SORT_TYPE(BAD_REQUEST, "INVALID_SORT_TYPE", "정렬 타입이 필요합니다."),
    INVALID_AUTHENTICATION(UNAUTHORIZED, "INVALID_AUTHENTICATION", "인증 정보를 찾을 수 없습니다."),

    // 리뷰 도메인 에러 - 유효성 검증
    EMPTY_REVIEW_CONTENT(BAD_REQUEST, "EMPTY_REVIEW_CONTENT", "리뷰 내용은 필수입니다."),
    REVIEW_CONTENT_TOO_LONG(BAD_REQUEST, "REVIEW_CONTENT_TOO_LONG", "리뷰 내용은 300자를 초과할 수 없습니다."),
    MISSING_RATING(BAD_REQUEST, "MISSING_RATING", "평점은 필수입니다."),
    INVALID_RATING(BAD_REQUEST, "INVALID_RATING", "평점은 1-5 사이의 값이어야 합니다."),

    // 리뷰 도메인 에러 - 비즈니스 규칙
    DUPLICATE_REVIEW(CONFLICT, "DUPLICATE_REVIEW", "이미 해당 주문에 대한 리뷰가 존재합니다."),
    UPDATE_TIME_EXPIRED(BAD_REQUEST, "UPDATE_TIME_EXPIRED", "리뷰는 작성 후 24시간 내에만 수정 가능합니다."),
    REVIEW_UNAUTHORIZED_ACCESS(FORBIDDEN, "REVIEW_UNAUTHORIZED_ACCESS", "본인이 작성한 리뷰만 접근 가능합니다."),

    // 리뷰 이미지 에러
    REVIEW_IMAGE_TOO_MANY(BAD_REQUEST, "REVIEW_IMAGE_TOO_MANY", "한 번에 업로드할 수 있는 이미지 수를 초과했습니다."),
    REVIEW_IMAGE_LIMIT_EXCEEDED(BAD_REQUEST, "REVIEW_IMAGE_LIMIT_EXCEEDED", "리뷰당 이미지 등록 한도를 초과했습니다."),
    REVIEW_IMAGE_UPLOAD_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_IMAGE_UPLOAD_FAILED", "이미지 업로드에 실패했습니다."),
    REVIEW_IMAGE_DELETE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_IMAGE_DELETE_FAILED", "이미지 삭제에 실패했습니다."),
    REVIEW_IMAGE_EMPTY_FILE(BAD_REQUEST, "REVIEW_IMAGE_EMPTY_FILE", "빈 파일은 업로드할 수 없습니다."),
    REVIEW_IMAGE_TOO_LARGE(BAD_REQUEST, "REVIEW_IMAGE_TOO_LARGE", "이미지 파일 크기가 너무 큽니다."),
    REVIEW_IMAGE_INVALID_FORMAT(BAD_REQUEST, "REVIEW_IMAGE_INVALID_FORMAT", "지원하지 않는 이미지 형식입니다."),

    // 리뷰 답글 기본 작업 에러
    REVIEW_REPLY_CREATE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_REPLY_CREATE_FAILED", "리뷰 답글 생성에 실패했습니다."),
    REVIEW_REPLY_UPDATE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_REPLY_UPDATE_FAILED", "리뷰 답글 수정에 실패했습니다."),
    REVIEW_REPLY_DELETE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_REPLY_DELETE_FAILED", "리뷰 답글 삭제에 실패했습니다."),
    REVIEW_REPLY_LIST_FETCH_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_REPLY_LIST_FETCH_FAILED", "답글 리뷰 목록 조회에 실패했습니다."),
    REVIEW_REPLY_NOT_FOUND(NOT_FOUND, "REVIEW_REPLY_NOT_FOUND", "답글을 찾을 수 없습니다."),

    // 리뷰 답글 입력값 검증 에러
    INVALID_REPLY_ID(BAD_REQUEST, "INVALID_REPLY_ID", "유효하지 않은 답글 ID입니다."),
    EMPTY_REPLY_CONTENT(BAD_REQUEST, "EMPTY_REPLY_CONTENT", "답글 내용은 필수입니다."),
    REPLY_CONTENT_TOO_LONG(BAD_REQUEST, "REPLY_CONTENT_TOO_LONG", "답글 내용은 300자를 초과할 수 없습니다."),

    // 리뷰 답글 비즈니스 규칙 에러
    DUPLICATE_REPLY(CONFLICT, "DUPLICATE_REPLY", "이미 해당 리뷰에 답글이 존재합니다."),
    REPLY_UNAUTHORIZED_ACCESS(FORBIDDEN, "REPLY_UNAUTHORIZED_ACCESS", "본인이 작성한 답글만 접근 가능합니다."),
    REPLY_UPDATE_TIME_EXPIRED(BAD_REQUEST, "REPLY_UPDATE_TIME_EXPIRED", "답글은 작성 후 24시간 내에만 수정 가능합니다."),
    INSUFFICIENT_PERMISSION(FORBIDDEN, "INSUFFICIENT_PERMISSION", "권한이 부족합니다."),

    // 리뷰 좋아요 에러
    REVIEW_HELPFUL_CREATE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_HELPFUL_CREATE_FAILED", "리뷰 좋아요 생성에 실패했습니다."),
    REVIEW_HELPFUL_DELETE_FAILED(INTERNAL_SERVER_ERROR, "REVIEW_HELPFUL_DELETE_FAILED", "리뷰 좋아요 삭제에 실패했습니다."),
    REVIEW_HELPFUL_NOT_FOUND(NOT_FOUND, "REVIEW_HELPFUL_NOT_FOUND", "좋아요를 찾을 수 없습니다."),

    // 스트림 도메인 에러
    STREAM_NOT_FOUND(NOT_FOUND, "STREAM_NOT_FOUND", "스트림을 찾을 수 없습니다."),
    STREAM_CANNOT_BE_STARTED(BAD_REQUEST, "STREAM_CANNOT_BE_STARTED", "스트림을 시작할 수 없습니다."),
    STREAM_CANNOT_BE_ENDED(BAD_REQUEST, "STREAM_CANNOT_BE_ENDED", "스트림을 종료할 수 없습니다."),
    STREAM_OWNER_MISMATCH(FORBIDDEN, "STREAM_OWNER_MISMATCH", "스트림 소유자 정보가 일치하지 않습니다.");


    private final HttpStatus status;
    private final String code;
    private final String message;
    
    ErrorCode(HttpStatus status, String code, String message) {
        this.status = status;
        this.code = code;
        this.message = message;
    }
    
    public HttpStatus getStatus() {
        return status;
    }
    
    public String getCode() {
        return code;
    }
    
    public String getMessage() {
        return message;
    }
} 