server:
    address: 127.0.0.1
    port: 8080

spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

    datasource:
        url: jdbc:mysql://localhost:3306/kkulddip
        username:
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    security:
        oauth2:
            client:
                registration:
                    google-customer:
                        provider: google
                        client-id: your-google-client-id
                        client-secret: your-google-client-secret
                        scope:
                            - email
                            - profile
                        redirect-uri: http://localhost:8080/login/oauth2/code/google-customer
                        client-name: Google Customer Login
                    google-owner:
                        provider: google
                        client-id: your-google-client-id
                        client-secret: your-google-client-secret
                        scope:
                            - email
                            - profile
                        redirect-uri: http://localhost:8080/login/oauth2/code/google-owner
                        client-name: Google Owner Login


jwt:
    secret-key: mySecretKeyForJwtTokenGenerationMustBe256BitsLongForHS256Algorithm
    access-token-expiration: 3600
    refresh-token-expiration: 86400

logging:
    level:
        web: DEBUG
