server:
    address: ${API_SERVER_ADDRESS}
    port: ${API_SERVER_PORT}

spring:
    application:
        name: kkulddip

    config:
        import: optional:file:.env[.properties]

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
        properties:
            hibernate:
                format_sql: false
                use_sql_comments: false
                dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false

    security:
        oauth2:
            client:
                registration:
                    google-customer:
                        provider: google
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                        redirect-uri: ${GOOGLE_OAUTH2_REDIRECT_URI}
                        client-name: Google Customer Login
                    google-owner:
                        provider: google
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
                        scope:
                            - email
                            - profile
                        redirect-uri: ${GOOGLE_OAUTH2_REDIRECT_URI_OWNER}
                        client-name: Google Owner Login
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
                        user-name-attribute: id


springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400}

app:
    oauth2:
        success-redirect-url: ${OAUTH2_SUCCESS_REDIRECT_URL}
    cors:
        max-age-seconds: ${CORS_MAX_AGE_SECONDS}

toss:
    payments:
        test-secret-key: ${TOSS_SECRET_KEY}
        test-client-key: ${TOSS_CLIENT_KEY}
        base-url: https://api.tosspayments.com

logging:
    level:
        web: INFO