export const ROUTE_PATH = {
  INDEX: '/',
  HOME: '/',
  LIKE: '/like',
  SEARCH: '/search',
  MY: '/my',
  ORDER: '/order',
  ORDER_DETAIL: '/order/:orderId',
  NOTIFICATION: '/notification',
  LOGIN: '/login',
  AUTH_CALLBACK: '/auth-callback',
  PAY: '/pay',
  PAYMENT_SUCCESS: '/payment/success',
  PAYMENT_FAIL: '/payment/fail',
  NOT_FOUND: '*',
  REVIEW: '/stores/:storeId/reviews',
  REVIEW_CREATE: '/review/create',
  STORE: '/stores/:storeId',
  STREAMS: '/streams',
  STREAM_DETAIL: '/streams/:streamId',
} as const;
