export const ROUTE_PATH = {
  INDEX: '/',
  HOME: '/',
  LIKE: '/like',
  SEARCH: '/search',
  MY: '/my',
  ORDER: '/order',
  ORDER_DETAIL: '/order/:orderId',
  NOTIFICATIONS: '/notifications',
  LOGIN: '/login',
  PAYMENT: '/payment',
  CART: '/cart',
  NOT_FOUND: '*',
  REVIEW: '/store/:storeId/reviews',
} as const;
